language: go
go:
- 1.9
before_install:
- sudo wget https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -O dep
- sudo chmod +x dep
- sudo cp dep /usr/bin
install:
- make install_dependencies
script:
- make test
- make package-darwin
- make package-linux
after_success:
- make cover
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key:
    secure: TwxVb3DBFf6qwNLcFEyEntdjaZLiMoUYrA6dEMhkKvLNqW4YjrdDdm11SZ4mLB806uT4SABHzP5clI2L/lzIH6Je9CuZPdXhTUvfqqz+rDeKSuf9+NqzNSJLSlHwluwjWlz2wokk2kAhcjvJjt1h5FIoYXhJvf0aB1el4IXnGGvb86wPznwhesaxecv/hLPIzTjQxK0BuIpj2/QZFxlB/ATY1AxN3bjfXqdWmwgj65nTfgHJ8WnkhdL7IK7zNjX5/3BaQvMeQSkMfYs8zjKXU62D9qwYLl+ucrrRTfFMOfYeORMUhWv4Q4FVlLh4YyOS4nldamaIVy42Nx27AJ1UkqWfTVHz1mjlMkmbP9QnQ298SWIUIQIDf9koUg9v451HOvvSN46FV7dENVvH5bveNRQqgNT2PUIFlAzD5IzQGcYd2IUgZgfT8zn30jhTuiaN3qvqdsxAJqYxhfrv9eDnDxKVe13GXXgDH7+Hk0iD4Y9KHOr60RCJoy4N2w++FN96iVhA7mccZf2k4gMbjU5xb5layVrjQPgynN/xQGeGyeKeP1UMdHr1G0KEkwUuiKPcuaXpxwlGfPX2dzFth2KMJXQBMYNa+EgNYa6H26swisD24FZ4lV/N1YH5ZSoBAf/FZBG96ntBQZZQY71eqJ6hb3r0SMfOsiWIe+K2+tQix4w=
  file:
  - build/dist/gitflow-release.darwin-amd64.tar.gz
  - build/dist/gitflow-release.linux-amd64.tar.gz
  skip_cleanup: true
  on:
    repo: chentex/gitflow-release
    tags: true
notifications:
  slack:
    secure: FcMl8/orefkzlXGUZavMHmIqFJejbFwUvuNkkEguy5qZO13qJaof2Kz4/Rfoax9WETVlC+Qp99ulbRKwG63NPjkZLV7X2VUV3573+Gt4CfmkhuQKgV2MitauR4Wq/6zEBIhFaDJiAKaCz/mCzPDPeaqNm86uxJT9A02ziDi2uUJvW48JPifKBAKvoRKGn8fh1ZI6knLbsgPcnUvBDTo6PNi0SmBRLlFF50ul7/5dXfpsNb9kKVj4BKCOspb3hit6KDr7hYwecRPCW6Rk5NZAEq4JKR/LLJUNtz8xI4K6Mi5WdTDQDMJt/Cnmp6NwoYskT07tFPdv375U346WWPtVsH/jJAkdYkwwf2Hky9GFmFr8wZ4v7u7TVWkOJTg1aKUAFD2WLm9Z6lkz2k0tLMLwrMkNqyGwRdQwN2Qk1O6XcBfdJtEC9QkW5+EWUrXH2nDdAfUmikrPlXdhNPcKLt6b71LQz9hlTtSRTn2B95wa0fhhPQb8+gJR0rXDbkAY//2A9I2eAc9zPtFMZPrWYxjwTbWHn/ApbVKvWhwPRT+RxaBbMcdLY+5p5fh5+v7DhYplLhXzrxeAUddJc9WOqYrhb9xtxzW76EyH+0eJVtusRIBEkgniysqw//y3v6G97qGsfALMfehGjbZA4wEXwVxbI6brY7XTCn2ATZD9qw0chAE=
